# See https://pre-commit.com/ for usage and config
default_language_version:
    python: python3.10
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: check-case-conflict
    - id: debug-statements
    - id: check-yaml
      args: [--allow-multiple-documents, --unsafe]
- repo: https://github.com/timothycrosley/isort
  rev: "5.12.0"
  hooks:
    - id: isort
      pass_filenames: true
- repo: local
  hooks:
  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    types: [python]
    exclude: setup.py

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: poetry run pytest . --ignore functional_tests/ -s
    types: [python]
    pass_filenames: false

  - id: pytest-cov
    name: pytest
    stages: [push]
    language: system
    entry: poetry run pytest --cov --cov-fail-under=0
    types: [python]
    pass_filenames: false
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.33.0
  hooks:
  - id: markdownlint
    args: [--fix, --disable, MD013]
