version: "3"
services:
  iambic-cicd:
    # NOTE: This compose file loads the image from ECR, not from what you are running
    # locally.
    image: public.ecr.aws/iambic/iambic:latest
    environment:
      - IAMBIC_CONFIG
      - IAMBIC_CONFIG_ASSUME_ROLE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - AWS_REGION
    volumes:
      - ~/.aws:/root/.aws:cached
    entrypoint: ""
    command:
      - "python"
      - "-m"
      - "iambic.lambda.app"
      - "import"
