version: "3"
services:
  iambic:
    environment:
      - IAMBIC_CONFIG
      - AWS_PROFILE
      - IAMBIC_CONFIG_ASSUME_ROLE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    build:
      context: .
      dockerfile: Dockerfile
    image: iambic
    ports:
      - 9000:8080
    volumes:
      - ~/.aws:/root/.aws:cached
      - .:/app:cached
    entrypoint:
      - "/usr/bin/aws-lambda-rie"
      - "/usr/bin/python"
      - "-m"
      - "awslambdaric"
    command: "iambic.lambda.app.handler"
